### ISSUE TITLE
Parsing issue in ASN file.

### ISSUE THREAD

**Issue by sagarchalise** [kimgr/asn1ate#10] opened 2014-11-10 09:09 UTC
Hello, I am quite new to ASN and parsing and this may be naive problem. I am trying to use your library to generate pyasn1 file from this ASN

http://jayu.googlecode.com/svn-history/r3/trunk/jayu/src/test/testdata/Huawie.txt

But I am getting exception.

```
pyparsing.ParseException: Expected "END" (at char 97715), (line:1110, col:32)
```

Could you help me with this issue ?

**Comment by kimgr** [comment] 2015-02-01 20:11
Duplicate of issue #15, fixed in 861f49d5b84470ba351c84d501e1a0fa3cd4d400

**Closed by kimgr** 2015-02-01 20:11 UTC
